spring:
  main:
    web-application-type: none
  session:
    store-type: none
  devtools:
    restart:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

server:
  port: 0

judge:
  worker:
    enabled: true
